import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.scss';
import { Footer, Header } from '../components';
import { CartProvider } from '@/context/cart';
import { Sidebar } from '@/shared/components';
import styles from './layout.module.scss';

const montserrat = Montserrat({
  subsets: ['cyrillic'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <CartProvider>
          <Header />
          <div className={styles.mainLayout}>
            <main className={styles.mainContent}>{children}</main>
          </div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
