import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.scss';
import { Footer, Header } from '../components';
import styles from './layout.module.scss';
import ClientProviders from '@/components/сlientProviders/ClientProviders';


const montserrat = Montserrat({
  subsets: ['cyrillic'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
          <ClientProviders>
          <div className={styles.layout}>
            <Header />
            <main className={styles.main}>{children}</main>
            <Footer />
          </div>
          </ClientProviders>
      </body>
    </html>
  );
}
